apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-1wxa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-1wxa
    app.kubernetes.io/part-of: my-app
  name: pacman-1wxa
  namespace: burrzinga-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: pacman-1wxa
    weight: null
status: {}
