apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-1wxa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-1wxa
    app.kubernetes.io/part-of: my-app
  name: pacman-1wxa
  namespace: burrzinga-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: pacman-1wxa
status:
  loadBalancer: {}
